# Generated by Django 5.1.4 on 2024-12-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruiz_clinic', '0005_appointment_app_contact_alter_appointment_app_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='app_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Waiting', 'Waiting'), ('Done', 'Done')], default='Waiting', max_length=50),
        ),
    ]
